kind = "web"
previewPath = "/"
title = "OptMails"
version = "1.0.0"
id = "artifacts/optmails"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21079

[services.development]
run = "pnpm --filter @workspace/optmails run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/optmails", "run", "build" ]
publicDir = "artifacts/optmails/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21079"
BASE_PATH = "/"
